export const HOUSES_LOADING = 'HOUSES_LOADING';
export const ADD_HOUSES = 'ADD_HOUSES';
export const HOUSES_FAILED = 'HOUSES_FAILED';

export const ADD_REVIEWS = 'ADD_REVIEWS';
export const REVIEWS_FAILED = 'REVIEWS_FAILED';

export const NEWTON_LOADING = 'NEWTON_LOADING';
export const ADD_NEWTON = 'ADD_NEWTON';
export const NEWTON_FAILED = 'NEWTON_FAILED';

export const VENDORS_LOADING = 'VENDORS_LOADING';
export const ADD_VENDORS = 'ADD_VENDORS';
export const VENDORS_FAILED = 'VENDORS_FAILED';